### ISSUE TITLE
咨询下

### ISSUE THREAD

**Issue by swy1996** [ylen0l/Hackintosh-Hp-Prodesk-400g2-DM-Clover-Efi#1]
麻烦咨询一下 我看你这是标压u 能正常使用么 
 需要更换更大的电源么？

**Comment by xia54** [comment]
电源我没换，主板功耗墙的原因你上90W电源也无济于事，我把散热换成铜的了，然而并没有什么卵用，温度和自带的铝散热没差别
![DED3E757-20F5-4F97-971E-7669F8CDDCD4_1_105_c](https://user-images.githubusercontent.com/64279486/83322285-e2a5f380-a288-11ea-99b9-f9a54dc2f41f.jpeg)
![2B3C92D3-7F2E-41CF-8AFB-9F127900EC9C_1_105_c](https://user-images.githubusercontent.com/64279486/83322289-e9cd0180-a288-11ea-9864-8167c2dcb9d4.jpeg)

**Comment by ylen0l** [comment]
![2B3C92D3-7F2E-41CF-8AFB-9F127900EC9C_1_105_c](https://user-images.githubusercontent.com/64279486/83322725-af656380-a28c-11ea-9bb0-cb4643d67295.jpeg)
![DED3E757-20F5-4F97-971E-7669F8CDDCD4_1_105_c](https://user-images.githubusercontent.com/64279486/83322731-ba1ff880-a28c-11ea-9600-7dba8158005b.jpeg)

**Comment by ylen0l** [comment]
![avatar](https://user-images.githubusercontent.com/64279486/83322747-d91e8a80-a28c-11ea-8a63-4936dbb883be.jpeg)
![avatar](https://user-images.githubusercontent.com/64279486/83322771-fce1d080-a28c-11ea-8181-cf202730e8b1.jpeg)
